[package]
name = "wood_box"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "a new description and version number"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
