[package]
name = "wood_box"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A scentence or two. John 1:1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
